#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [[ $TRAVIS == "true" ]]; then
  BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
else
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
fi
if [[ $BRANCH == "master" ]]; then
  TAG="latest"
else
  TAG=$BRANCH
fi
if ! docker inspect postgres &> /dev/null; then
  docker run --detach --name postgres postgres
fi
exec docker run \
  --name boggle \
  --interactive \
  --tty \
  --rm \
  --env ENVIRONMENT="$ENVIRONMENT" \
  --link postgres:postgres \
  --mount type=bind,source="$DIR",target=/code/boggle \
  --publish 8000:8000 \
  "zackhsi/boggle:$TAG" \
  "$@"
